apiVersion: v1
kind: Service

metadata:
  name: upload-server-svc
  namespace: upload-server
spec:
  type: ClusterIP
  selector:
    app: upload-server
  ports:
    - port: 80
      targetPort: 3333

---
apiVersion: v1
kind: Service

metadata:
  name: upload-server-preview-svc
  namespace: upload-server
spec:
  type: ClusterIP
  selector:
    app: upload-server
  ports:
    - port: 80
      targetPort: 3333
